name: flutterpp
description: flutterpp is a desktop app for creating and managing Flutter projects.
publish_to: "none"
version: 0.0.9
environment:
  sdk: ^3.5.0

# dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  window_manager: ^0.3.8
  get_storage: ^2.1.1
  supabase_flutter: ^2.3.4
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^11.0.0
  heroicons: ^0.11.0
  loading_animation_widget: ^1.2.0+4
  uuid: ^4.3.3
  flutter_svg: ^2.0.6
  expansion_tile_group: ^2.0.0
  google_fonts: ^6.1.0
  flex_color_picker: ^3.2.2
  sizer: ^3.0.3
  file_selector: ^1.0.2
  awesome_side_sheet: ^0.0.3
  device_frame: ^1.1.0
  flutter_platform_alert: ^0.6.1
  screenshot: ^3.0.0
  image: ^4.1.4
  process_run: ^1.1.0
  glowy_borders: ^1.0.2
  device_info_plus: ^10.1.2
  lottie: ^3.0.0
  json2yaml: ^3.0.1
  yaml: ^3.1.2
  widget_arrows: ^0.6.0
  graphite: ^1.1.2
  appflowy_editor: ^4.0.0
  emojis: ^0.9.9
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.0.2
  dashed_circular_progress_bar: ^0.0.6
  animated_flip_counter: ^0.3.4
  currency_picker: ^2.0.20
  flutter_launcher_icons: ^0.14.2
  tab_container: ^3.5.3
  syntax_highlight: ^0.4.0
  clipboard: ^0.1.3
  system_tray: ^2.0.3
  updat: ^1.3.2
  sentry_flutter: ^8.8.0-alpha.1
  feedback: ^3.0.0
  flutter_markdown: ^0.6.20+1
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  flex_color_scheme: ^8.1.0
  flutter_dotenv: ^5.1.0
  printing: ^5.13.4
  # pdf: ^3.10.7



dependency_overrides:
  uuid: ^4.5.1
  # printing:
  #   git:
  #     url: https://github.com/DavBfr/dart_pdf.git
  #     ref: macos-WKWebView
  #     path: printing

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/screenshots/
    - assets/templates/
    - assets/jsons/
    - assets/lottie/
    - assets/cers/
    - .env

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  windows:
    generate: true
  macos:
    generate: true
