// return title up config
Map<String, dynamic> deviceAdvanceRotateRightTitleDown() {
  // return TemplateLayoutConfig(
  //   type: TemplateLayoutEnum.deviceAdvanceRotateRightTitleDown,
  //   bodyDirection: Axis.horizontal,
  //   bodyVerticalDirection: VerticalDirection.up,
  //   bodyCrossAxisAlignment: WrapCrossAlignment.center,
  //   logoAlignment: MainAxisAlignment.end,
  //   titleAlignment: MainAxisAlignment.end,
  //   subtitleAlignment: MainAxisAlignment.end,
  //   devicePositionTop: 180,
  //   devicePositionRight: null,
  //   devicePositionLeft: -60,
  //   devicePositionBottom: null,
  //   bodyRunSpacing: 0,
  //   bodySpacing: 0,
  //   rotate: 0.38,
  //   titlePaddingTop: 30,
  //   titlePaddingBottom: 0,
  //   titlePaddingLeft: 20,
  //   titlePaddingRight: 20,
  //   subtitlePaddingTop: 0,
  //   subtitlePaddingBottom: 20,
  //   subtitlePaddingLeft: 20,
  //   subtitlePaddingRight: 20,
  //   logoPaddingTop: 0,
  //   logoPaddingBottom: 0,
  //   logoPaddingLeft: 20,
  //   logoPaddingRight: 20,
  //   showLogo: false,
  //   showTitle: true,
  //   deviceFullSize: false,
  //   showSubtitle: true,
  //   title: 'Your Title',
  //   subtitle: 'your Subtitle',
  // );

  // json
  return {
    "type": "deviceAdvanceRotateRightTitleDown",
    "bodyDirection": "horizontal",
    "bodyVerticalDirection": "up",
    "bodyCrossAxisAlignment": "center",
    "logoAlignment": "end",
    "titleAlignment": "end",
    "subtitleAlignment": "end",
    "devicePositionTop": 176.0,
    "devicePositionRight": 113.0,
    "devicePositionLeft": null,
    "devicePositionBottom": null,
    "bodyRunSpacing": 0.0,
    "bodySpacing": 0.0,
    "rotate": 0.104,
    "titlePaddingTop": 0.0,
    "titlePaddingBottom": 0.0,
    "titlePaddingLeft": 20.0,
    "titlePaddingRight": 20.0,
    "subtitlePaddingTop": 0.0,
    "subtitlePaddingBottom": 20.0,
    "subtitlePaddingLeft": 20.0,
    "subtitlePaddingRight": 20.0,
    "logoPaddingTop": 0.0,
    "logoPaddingBottom": 0.0,
    "logoPaddingLeft": 20.0,
    "logoPaddingRight": 20.0,
    "showLogo": false,
    "showTitle": true,
    "deviceFullSize": false,
    "showSubtitle": true,
    "title": "Your Title",
    "subtitle": "your Subtitle"
  };
}
