// return title up config
Map<String, dynamic> deviceRotateRightTitleUp() {
  // return TemplateLayoutConfig(
  //   type: TemplateLayoutEnum.deviceRotateRightTitleUp,
  //   bodyDirection: Axis.horizontal,
  //   bodyVerticalDirection: VerticalDirection.down,
  //   bodyCrossAxisAlignment: WrapCrossAlignment.center,
  //   logoAlignment: MainAxisAlignment.start,
  //   titleAlignment: MainAxisAlignment.start,
  //   subtitleAlignment: MainAxisAlignment.start,
  //   devicePositionTop: -130,
  //   devicePositionRight: -150,
  //   devicePositionLeft: null,
  //   devicePositionBottom: null,
  //   bodyRunSpacing: 0,
  //   bodySpacing: 0,
  //   rotate: 0.104,
  //   titlePaddingTop: 30,
  //   titlePaddingBottom: 0,
  //   titlePaddingLeft: 20,
  //   titlePaddingRight: 20,
  //   subtitlePaddingTop: 0,
  //   subtitlePaddingBottom: 0,
  //   subtitlePaddingLeft: 20,
  //   subtitlePaddingRight: 20,
  //   logoPaddingTop: 20,
  //   logoPaddingBottom: 20,
  //   logoPaddingLeft: 20,
  //   logoPaddingRight: 20,
  //   showLogo: false,
  //   showTitle: true,
  //   deviceFullSize: true,
  //   showSubtitle: true,
  //   title: 'Your Title',
  //   subtitle: 'your Subtitle',
  // );

  // json
  return {
    "type": "deviceRotateRightTitleUp",
    "bodyDirection": "horizontal",
    "bodyVerticalDirection": "down",
    "bodyCrossAxisAlignment": "center",
    "logoAlignment": "start",
    "titleAlignment": "start",
    "subtitleAlignment": "start",
    "devicePositionTop": -80,
    "devicePositionRight": -140.0,
    "devicePositionLeft": null,
    "devicePositionBottom": null,
    "bodyRunSpacing": 0.0,
    "bodySpacing": 0.0,
    "rotate": 0.104,
    "titlePaddingTop": 30.0,
    "titlePaddingBottom": 0.0,
    "titlePaddingLeft": 20.0,
    "titlePaddingRight": 20.0,
    "subtitlePaddingTop": 0.0,
    "subtitlePaddingBottom": 0.0,
    "subtitlePaddingLeft": 20.0,
    "subtitlePaddingRight": 20.0,
    "logoPaddingTop": 20.0,
    "logoPaddingBottom": 20.0,
    "logoPaddingLeft": 20.0,
    "logoPaddingRight": 20.0,
    "showLogo": false,
    "showTitle": true,
    "deviceFullSize": false,
    "showSubtitle": true,
    "title": "Your Title",
    "subtitle": "your Subtitle"
  };
}
