// return right side title up config
Map<String, dynamic> rightSideTitleDown() {
  // return TemplateLayoutConfig(
  //   type: TemplateLayoutEnum.rightSideTitleUp,
  //   bodyDirection: Axis.horizontal,
  //   bodyVerticalDirection: VerticalDirection.up,
  //   bodyCrossAxisAlignment: WrapCrossAlignment.center,
  //   logoAlignment: MainAxisAlignment.center,
  //   titleAlignment: MainAxisAlignment.center,
  //   subtitleAlignment: MainAxisAlignment.center,
  //   devicePositionTop: null,
  //   devicePositionLeft: 155,
  //   devicePositionRight: null,
  //   devicePositionBottom: null,
  //   bodyRunSpacing: 20,
  //   bodySpacing: 20,
  //   rotate: 0,
  //   titlePaddingTop: 0,
  //   titlePaddingBottom: 0,
  //   titlePaddingLeft: 0,
  //   titlePaddingRight: 0,
  //   subtitlePaddingTop: 0,
  //   subtitlePaddingBottom: 30,
  //   subtitlePaddingLeft: 0,
  //   subtitlePaddingRight: 0,
  //   logoPaddingTop: 20,
  //   logoPaddingBottom: 20,
  //   logoPaddingLeft: 20,
  //   logoPaddingRight: 20,
  //   showLogo: false,
  //   showTitle: true,
  //   showSubtitle: true,
  //   title: 'Your Title',
  //   subtitle: 'your Subtitle',
  // );

  // json
  return {
    "type": "rightSideTitleDown",
    "bodyDirection": "horizontal",
    "bodyVerticalDirection": "up",
    "bodyCrossAxisAlignment": "center",
    "logoAlignment": "center",
    "titleAlignment": "center",
    "subtitleAlignment": "center",
    "devicePositionTop": null,
    "devicePositionLeft": 155.0,
    "devicePositionRight": null,
    "devicePositionBottom": null,
    "bodyRunSpacing": 20.0,
    "bodySpacing": 20.0,
    "rotate": 0.0,
    "titlePaddingTop": 0.0,
    "titlePaddingBottom": 0.0,
    "titlePaddingLeft": 0.0,
    "titlePaddingRight": 0.0,
    "subtitlePaddingTop": 0.0,
    "subtitlePaddingBottom": 30.0,
    "subtitlePaddingLeft": 0.0,
    "subtitlePaddingRight": 0.0,
    "logoPaddingTop": 20.0,
    "logoPaddingBottom": 20.0,
    "logoPaddingLeft": 20.0,
    "logoPaddingRight": 20.0,
    "showLogo": false,
    "showTitle": true,
    "showSubtitle": true,
    "title": "Your Title",
    "subtitle": "your Subtitle"
  };
}
