// return title up config
Map<String, dynamic> titleUp() {
  // json
  return {
    "type": "titleUp",
    "title": "Your Title",
    "subtitle": "your Subtitle",
    "bodyDirection": "horizontal",
    "bodyVerticalDirection": "down",
    "bodyCrossAxisAlignment": "center",
    "logoAlignment": "center",
    "titleAlignment": "center",
    "subtitleAlignment": "center",
    "firstDevicePositionTopBottom": 0,
    "firstDevicePositionRightLeft,": 0,
    "secondDevicePositionTopBottom,": 0,
    "secondDevicePositionRightLeft,": 0,
    "bodyRunSpacing": 0,
    "bodySpacing": 0,
    "rotate": 0.0,
    "titlePaddingTop": 0.0,
    "titlePaddingBottom": 0.0,
    "titlePaddingLeft": 0.0,
    "titlePaddingRight": 0.0,
    "subtitlePaddingTop": 0.0,
    "subtitlePaddingBottom": 0.0,
    "subtitlePaddingLeft": 0.0,
    "subtitlePaddingRight": 0.0,
    "logoPaddingTop": 0.0,
    "logoPaddingBottom": 0.0,
    "logoPaddingLeft": 0.0,
    "logoPaddingRight": 0.0,
    "gradientAngle": 0.0,
    "showLogo": false,
    "showSecondLogo": false,
    "showTitle": true,
    "showSubtitle": true,
    "deviceFullSize": false,
    "secondDeviceFullSize": false,
    "showDevice": true,
    "showSecondDevice": false,
    "showFrame": true,
    "showSecondFrame": true,
  };
}
