enum TemplateLayoutEnum {
  defaultLayout,
  titleUp,
  titleDown,
  rightSideTitleUp,
  leftSideTitleUp,
  rightSideTitleDown,
  leftSideTitleDown,
  deviceRotateRightTitleUp,
  deviceRotateRightTitleDown,
  deviceRotateLeftTitleUp,
  deviceRotateLeftTitleDown,
  deviceAdvanceRotateRightTitleUp,
  deviceAdvanceRotateRightTitleDown,
  deviceAdvanceRotateLeftTitleUp,
  deviceAdvanceRotateLeftTitleDown,
}
